### PR TITLE
Upgrading, reforming and pruning the Exceptions (#5808)

### LINKED ISSUE #5808: How the Exceptions implemented and upgrading align with .NET 8 standards.
### Is there an existing issue for this?

- [X] I have searched the existing issues

In the [Exceptions directory](https://github.com/bitfoundation/bitplatform/tree/develop/src/BlazorUI/Demo/Shared/Exceptions) we are facing with this warning :

``'ApplicationException.ApplicationException(SerializationInfo, StreamingContext)' is obsolete: 'This API supports obsolete formatter-based serialization. It should not be called or extended by application code.'SYSLIB0051``

According to the Microsoft documents  ``The following kinds of APIs are obsolete, starting in .NET 8. Calling them in code generates warning SYSLIB0051 at compile time.``
[learn.microsoft.com](https://learn.microsoft.com/en-us/dotnet/fundamentals/syslib-diagnostics/syslib0051)
[dotnet #34893](https://github.com/dotnet/docs/issues/34893)

Thus it's better to avoid Deriving from ApplicationException: It is considered a best practice in .NET to derive your custom exceptions directly from System.Exception or more specific exceptions if applicable. ApplicationException was originally intended to be the base class for application-defined exceptions, but its use is no longer recommended.
Also we can safely remove the Obsolete Constructor ``UnknownException(SerializationInfo, StreamingContext)`` from the [KnownException](https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Demo/Shared/Exceptions/KnownException.cs ) and [UnknownException](https://github.com/bitfoundation/bitplatform/blob/develop/src/BlazorUI/Demo/Shared/Exceptions/UnknownException.cs) constructors to get rid of the warning since we do not need custom serialization logic for our exceptions.

Please Check [Pull request #5809](https://github.com/bitfoundation/bitplatform/pull/5809)

### PR DESCRIPTION
**Pull request by zandiarash**
this closes #5808

### CODE REVIEW

**Comment by msynk** [comment]
@zandiarash Thanks a lot.
There are a few other projects that need these changes. could you please take care of those too?
(like project templates and websites)

**Comment by zandiarash** [comment]
> @zandiarash Thanks a lot. There are a few other projects that need these changes. could you please take care of those too? (like project templates and websites)

Certainly! I'll do my best.

**Comment by zandiarash** [comment]
> @zandiarash Thanks a lot. There are a few other projects that need these changes. could you please take care of those too? (like project templates and websites)

The task is complete. You can now proceed with the merge.Also I noticed the variable name 'appSettings' varied in certain sections, so I've standardized it for consistency.

**Comment by msynk** [comment]
@zandiarash Thanks for the updates, but we do not accept changes that are not related to the issue.
So please file a new Issue for the `appSettings` change suggestion.

**Comment by zandiarash** [comment]
> @zandiarash Thanks a lot for the updates, but we do not accept changes that are not related to the issue. So if you can, please file a new Issue for the `appSettings` change suggestion.

I've rolled back to the previous state, focusing solely on modifying the Exceptions. I'll create a separate issue for the ``appSettings`` later on.

**Review by msynk — APPROVED** [review]

**Pull request merged**
