### PR TITLE
Add placeholder unit test for NumericTextField #2244

### LINKED ISSUE #2244: Unit Tests for the new `Placeholder` parameter of the `BitNumericTextField` component
It is required to provide suitable unit tests for the `Placeholder` parameter of the `BitNumericTextField `component, which will be implemented in #2243.

### PR DESCRIPTION
**Pull request by Md23Mh**
This closes #2244

### CODE REVIEW

**Review by msynk — CHANGES_REQUESTED** [review]
It seems you've copied a single test method to all types of the NumbericTextField tests.
it is better to have a general test for these types of tests, so we don't have to implement these tests in all of the other ones.

**Comment by msynk** [comment]
@Md23Mh ?

**Comment by Md23Mh** [comment]
Yep precisely! I did it because it is what apparently happened to some test methods for this component, and I just followed the rule here.

**Comment by msynk** [comment]
@Md23Mh 
yeah, I know about other methods. but please update the PR based on my previous comment.

**Review by msynk — APPROVED** [review]

**Pull request merged**
