### PR TITLE
Header button issue in small screens in the Playground project (#1980)

### LINKED ISSUE #1980: Header button issue in small screens in the `Playground` project
The header button shown in the image below must not be displayed in small screen sizes:

photo_2022-05-09_17-22-05

### PR DESCRIPTION
**Pull request by sajadkardel**
this closes #1980

### CODE REVIEW

**Review by msynk — APPROVED** [review]

**Comment by maryamhdr** [comment]
I think this solution is not correct.
You should check the mixin written for HeaderPrimaryBtn in this file src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Styles/abstracts/_mixins.scss.

@sajadkardel

**Comment by msynk** [comment]
@maryamhdr 
on which item this PR is pending?

**Comment by maryamhdr** [comment]
> @maryamhdr on which item this PR is pending?
This PR is pending because its corresponding issue needs more investigation to determine the scenario in which the issue takes place.

**Comment by maryamhdr** [comment]
The provided solution is not correct, so I close this PR.

**Pull request closed without merging**
