### PR TITLE
Simplify the JWT claim types in the `TodoTemplate` project (#1800) 

### LINKED ISSUE #1800: Simplify the Claim names in the JWT token of the `TodoTemplate` project
Currently, the names used for the Claims of the JWT Token of the template project are coming from the `ClaimTypes` class which are very long strings like `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier`. It is better to simplify these names in a way that both client and server benefit from them.

### PR DESCRIPTION
**Pull request by ysmoradi**
This closes #1800

### CODE REVIEW

**Comment by msynk** [comment]
what is this PR's issue?

**Comment by ysmoradi** [comment]
#2144 is duplicate #1800

**Comment by msynk** [comment]
Hmm, #2144 is this PR, and #1800 is an issue, so a duplication is not what we have here.

**Comment by ysmoradi** [comment]
Yes, I fixed that!

**Review by msynk — APPROVED** [review]

**Pull request merged**
